### PR TITLE
Add a parent/acceptor event loop group, use setIoRatio with epoll

### PR DESCRIPTION
**Pull request by wjoel**

### CODE REVIEW

**Comment by wjoel** [comment]
I'll re-target for `series/0.4` later today.

**Comment by wjoel** [comment]
Not re-targeting after all, as this conflicts with https://github.com/http4s/http4s-netty/commit/34bc4fb9bb7d680bad8ed48556f01abfe0c6314f - that commit does much the same as this, but doesn't allow for using different `setIoRatio` for the boss/parent/acceptor and the workers, as vert.x does with `100` in https://github.com/eclipse-vertx/vert.x/blob/daf5bbcc65eea5829556bb03ba0d30085d187dba/src/main/java/io/vertx/core/impl/VertxImpl.java#L158

**Comment by hamnis** [comment]
Lets do this instead. My approach was just to avoid duplication.

Needs a scalafmt.

**Comment by hamnis** [comment]
Merged then backported to series/0.4

**Pull request merged**
