### PR TITLE
Reuse the RFC7231InstantFormatter for all Netty Channels

### PR DESCRIPTION
**Pull request by bryce-anderson**
Problem

A new DateTimeFormatter is created for each Netty Channel. In the HTTP/2 flow this can start to add up as each dispatch will get its own Channel.

Solution

Create it once in the object and share it. The DateTimeFormatter type is immutable and thread safe so there is no reason not to.

### CODE REVIEW

**Comment by hamnis** [comment]
test failure is a flaky test. Not related to this change.

**Comment by hamnis** [comment]
thanks

**Comment by rossabaker** [comment]
That's a nice name to see back at the top of the changelog!

**Comment by bryce-anderson** [comment]
> That's a nice name to see back at the top of the changelog!

Haha, I couldn't help it: I love this stuff. Maybe the next one will be more exciting. Maybe not 😉.

**Pull request merged**
