### PR TITLE
Use the Netty EventLoop for execution in the Http4sNettyHandler

### PR DESCRIPTION
**Pull request by bryce-anderson**
Problem

The Netty pipelines expect you to be in the EventLoop thread associated with that pipeline when you perform pipeline events such as calling ctx.read(), ctx.write(..), etc. If you're not, events are shifted on your behalf into the channels event loop. This shifting can make it tough to reason about when events will occur, and in what order.

The comment about the Trampoline enforcing write orders is also a bit misleading: the trampoline is a thread-local construct so it doesn't enforce any ordering between different threads. It is the sequencing of the Futures that is really enforcing the desired ordering: the Future[(Response,Cleanup)], while it may be ready in any order, is not acted upon (via the contents in .map {..}) until the previous has finished and thus let the flatMap operation proceed.

Solution

Instead of using a Trampoline ExecutionContext we instead just use the Netty EventLoop directly. This gives us all the same properties we wanted, namely serial execution of events, but also makes our Netty events immediately traverse the pipeline.

### CODE REVIEW

**Comment by bryce-anderson** [comment]
This is part of a larger piece of work that can be found in this branch [here](https://github.com/bryce-anderson/http4s-netty/tree/requestCancellation).

It looks like there are a few binary incompatibilities. Most of the changes are to internal types but it appears that the `object Http4sNettyHandler` is public, and thus it's `def websocket` method is also public. We technically have access to the `Channel` via the `ChannelHandlerContext` and can initialize the field lazily if we want to preserve the `def websocket` methods API.

**Comment by hamnis** [comment]
if we keep the Trampoline around, but not use it. then mima should be happy.
Will remove the trampoline in main.

**Comment by bryce-anderson** [comment]
> if we keep the Trampoline around, but not use it. then mima should be happy.
> Will remove the trampoline in main.

Deal. I'll bring it back to life.

**Comment by hamnis** [comment]
thanks

**Comment by bryce-anderson** [comment]
> thanks

You're welcome!

**Pull request merged**
